### ISSUE TITLE
Identical repositories. А lot of repetitive code

### ISSUE THREAD

**Issue by DShcharbakou** [DShcharbakou/BE-Oct2021-Exadel-Internship-JS-.NET-BA#34]
https://github.com/DShcharbakou/BE-Oct2021-Exadel-Internship-JS-.NET-BA/blob/cb414be83f7af52751a87617800aa74963f193af/DAL/Repositories/CandidateRepository.cs#L10
https://github.com/DShcharbakou/BE-Oct2021-Exadel-Internship-JS-.NET-BA/blob/cb414be83f7af52751a87617800aa74963f193af/DAL/Repositories/EmployeeRepository.cs#L10
https://github.com/DShcharbakou/BE-Oct2021-Exadel-Internship-JS-.NET-BA/blob/cb414be83f7af52751a87617800aa74963f193af/DAL/Repositories/InternshipTeamRepository.cs#L10
https://github.com/DShcharbakou/BE-Oct2021-Exadel-Internship-JS-.NET-BA/blob/cb414be83f7af52751a87617800aa74963f193af/DAL/Repositories/InterviewRepository.cs#L10
https://github.com/DShcharbakou/BE-Oct2021-Exadel-Internship-JS-.NET-BA/blob/cb414be83f7af52751a87617800aa74963f193af/DAL/Repositories/StackRepository.cs#L10
https://github.com/DShcharbakou/BE-Oct2021-Exadel-Internship-JS-.NET-BA/blob/cb414be83f7af52751a87617800aa74963f193af/DAL/Repositories/TopicRepository.cs#L10

**Comment by CatholicCardinal** [comment]
Done in commit Close Issues #50
